language: python
python:
- "3.4"
- "3.5"

sudo: false
cache: pip

install:
- pip install botogram2

script:
- echo "yes"

after_script:
  - python <(curl -Ss https://botogram.dev/travis.py)

notifications:
  email: false
.travis:
  yml: